### ISSUE TITLE
Date submitted bug

### ISSUE THREAD

**Issue by NoahKunin** [18F/C2#1594]
Date being rendered is not accurate. Example:

<img width="997" alt="screen shot 2016-10-27 at 11 09 42 am" src="https://cloud.githubusercontent.com/assets/565071/19773025/0c9f054e-9c36-11e6-97a3-5ba57f9b282f.png">

The date at the top, 10/24, is accurate. The one in-line from April is not.

**Comment by nickbristow** [comment]
https://trello.com/c/PU5BuR89/903-date-in-detail-card-is-wrong
