### ISSUE TITLE
Reporting/Filtering frontend

### ISSUE THREAD

**Issue by phirefly** [18F/C2#246]
Bring visibility to the following:
1. Total transactions
1. Total dollars spent (filter by: vendor, date)
1. Rejection data: amount of requests rejected and reasons why
1. Engagement time / average time to completion
1. Policy related: (e.g. split transactions)

/cc https://www.pivotaltracker.com/story/show/86061736

**Comment by afeld** [comment]
Lots more notes from a discussion w/ one of our users here: https://hackpad.com/Reporting-UI-Discussion-OAXBMZrZ5Uw

**Comment by jessieay** [comment]
Closing this, as the linked tracker story was accepted on May 12, 2015
