### ISSUE TITLE
Consolidate project documentation

### ISSUE THREAD

**Issue by afeld** [18F/C2#263]
We currently have documentation about the project scattered around:

* [The GItHub Pages site](http://18f.github.io/C2/)
* [The app homepage](https://cap.18f.us)
* [The README](https://github.com/18F/C2#readme)
* [The `doc/` folder](https://github.com/18F/C2/tree/master/doc)
* [The 18F Dashboard](https://18f.gsa.gov/dashboard/project/C2/)

which seems like too many. At the very least, I think we can make the messaging more consistent. There are a handful of audiences that we want to speak to:

* Program officers or other potential users / new use cases
* Current users looking to get more information
* New 18F teammates
* Potential outside contributors
* Curious passerby

Questions:

* What can we consolidate?
* Where should different pieces of information live?
* How should it be organized?

Would love some content (and content design) help!

/cc https://www.pivotaltracker.com/story/show/83786688

**Comment by jessieay** [comment]
Seems like this was dealt with -- there is no longer documentation in the README, and all of the other links are broken except for docs. Hooray!
