### ISSUE TITLE
Reporting concepts from SF hackathon 2015

### ISSUE THREAD

**Issue by carolaponce** [18F/C2#275]
![mir_compare_04](https://cloud.githubusercontent.com/assets/11700545/6883356/1d76d064-d567-11e4-9fb4-51084fbfaf15.jpg)
![mir_datapoint_03](https://cloud.githubusercontent.com/assets/11700545/6883359/1d95891e-d567-11e4-949e-7b5e5d123246.jpg)
![mir_graphgreen_02](https://cloud.githubusercontent.com/assets/11700545/6883357/1d919a5c-d567-11e4-95fb-cb78bd931c32.jpg)
![mir_initialscreen_01](https://cloud.githubusercontent.com/assets/11700545/6883358/1d955b24-d567-11e4-88c2-eb08e7053898.jpg)

**Comment by Strawb3rries** [comment]
![dashboard_ai_v1-05](https://cloud.githubusercontent.com/assets/11700607/6883454/c51043a2-d56a-11e4-9346-12be5002cdfc.png)

**Comment by Strawb3rries** [comment]
![1communicart_dashboard_ai-1](https://cloud.githubusercontent.com/assets/11700607/6883501/8982e36e-d56d-11e4-9f1a-0ab6987734a7.jpg)

**Comment by Strawb3rries** [comment]
![2communicart_dashboard_ai-2](https://cloud.githubusercontent.com/assets/11700607/6883503/910c4760-d56d-11e4-89a2-a5806da1921d.jpg)

**Comment by Strawb3rries** [comment]
![3communicart_dashboard-3](https://cloud.githubusercontent.com/assets/11700607/6883504/9a564b40-d56d-11e4-8db6-6dea696146d3.jpg)

**Comment by Strawb3rries** [comment]
![5communicart_dashboard_ai-5](https://cloud.githubusercontent.com/assets/11700607/6883506/a5d920dc-d56d-11e4-9136-92454e7bf882.jpg)

**Comment by Strawb3rries** [comment]
![communicart_dashboard_ai-03](https://cloud.githubusercontent.com/assets/11700607/6883507/b7b3f494-d56d-11e4-9f18-a745646bf065.jpg)

**Comment by Strawb3rries** [comment]
![communicart_dashboard_ai-04](https://cloud.githubusercontent.com/assets/11700607/6883511/cd0f52c0-d56d-11e4-8ae7-c01cfdd16263.jpg)

**Comment by Strawb3rries** [comment]
![communicart_dashboard_ai-02](https://cloud.githubusercontent.com/assets/11700607/6883513/d2eb17d8-d56d-11e4-802f-b6b6073dd712.jpg)

**Comment by jessieay** [comment]
Closing this since it is referenced in https://github.com/18F/C2/issues/246

Thank you!

Jessie
