### ISSUE TITLE
Suggest somebody put captioning Communicart video into Open Opportunities 

### ISSUE THREAD

**Issue by HobokenMartha** [18F/C2#312]
Because YouTube's automatic captioning...le sigh.  
![communicart](https://cloud.githubusercontent.com/assets/479371/7282981/650dc5ce-e901-11e4-9992-353697f95856.GIF)

**Comment by afeld** [comment]
Good idea, though that video is already woefully out-of-date :confused: Probably worth removing the video from the homepage with https://github.com/18F/C2/issues/281.
