### ISSUE TITLE
Text Fields should have character limits in DB and UI

### ISSUE THREAD

**Issue by anthonygarvan** [18F/C2#435]
If you enter in a long title, the server comes back with a 500. There does not seem to be a limit in the description field. For the title, a limit should be set so that it display properly on the UI. For the description, some large but reasonable limit should be set to guarantee limits on the data storage in the DB. When submitting a large (eg., 10 MB) description, the server comes back with 502: bad gateway. 1 MB descriptions go through just fine.

I realize this is mostly an internal tool and ideally you should not have malicious users, but it is good practice to always put limits on fields that the user provides.

**Comment by cmc333333** [comment]
Great point -- we should have limits both within the application and at the web server. We just switched to puma today. I wonder if it has better defaults for denying large requests.

https://www.pivotaltracker.com/story/show/98243246 is a story around the lower-level request limits
https://www.pivotaltracker.com/story/show/98243246 is a story around adding sensible string bounds

**Comment by jessieay** [comment]
So far, this has not been an issue in production. Will keep an eye on New Relic for errors.
