### ISSUE TITLE
Attachment data limits

### ISSUE THREAD

**Issue by anthonygarvan** [18F/C2#436]
There does not seem to be limits on the attachment data volume. I uploaded >50 MB worth of attachments and could submit the request just fine. There should also be a validation around the data size per attachment - a 10MB attachment went through fine, but 30 MB came back with a 502.   

There should be limits on the size of the attachment and the total number of attachments per request.

**Comment by cmc333333** [comment]
Good point. Again, we should add a restriction at the web server layer _and_ at the application layer.

https://www.pivotaltracker.com/story/show/98243368 for the story specifically around file size validation.

**Comment by jessieay** [comment]
added a tracker story for limiting file size and updating the version of paperclip we're using since ours is out of date https://www.pivotaltracker.com/story/show/108559154

closing this issue now
