### ISSUE TITLE
Suggested feature: view items ordered by office location (18F)

### ISSUE THREAD

**Issue by ethanheppner** [18F/C2#437]
This would be really helpful for avoiding duplicates where there are multiple requestors in the same office.

**Comment by afeld** [comment]
As the person approving, you mean? Or as the requester to make sure no one else has submitted the order yet?

**Comment by ethanheppner** [comment]
Both, if possible, would be useful.

**Comment by jessieay** [comment]
Created a tracker story for this here: https://www.pivotaltracker.com/story/show/108498108

Closing this issue now ;)
