### ISSUE TITLE
Suggested feature: send message with approval/decline

### ISSUE THREAD

**Issue by ethanheppner** [18F/C2#438]
According to Ric, these are two separate steps that would make more sense as one-- maybe allow the message/comment to be sent when "Approve" or "Deny" is hit?

**Comment by afeld** [comment]
What's an example of a comment that you/he would want to send with the approval? Sending a reason with a rejection makes sense to me.

/cc @ric7694 https://www.pivotaltracker.com/story/show/90514402

**Comment by ethanheppner** [comment]
Here's an example of a request that I made (for non-rechargeable batteries) that was rejected and updated in favor of rechargeable ones. The updated request was approved, but Ric wanted to provide additional clarification for future orders.

![screen shot 2015-07-02 at 8 46 43 am](https://cloud.githubusercontent.com/assets/12718798/8478437/ff920d68-2096-11e5-9746-8c1db4323423.png)

**Comment by jessieay** [comment]
We already allow cancellation comments (adding detail on why someone is cancelling, which is included in the cancellation email). 

There is a story for approval comments here: https://www.pivotaltracker.com/story/show/99161462

Closing this issue now :)
