### ISSUE TITLE
Usability Improvement: Validations, Comments, and Attachments through Client / AJAX

### ISSUE THREAD

**Issue by anthonygarvan** [18F/C2#444]
The request submission page has way too many page refreshes. Validations should be done on the client side (I see you already have a case for that - 98157690). Comments and attachments should be done through AJAX.

**Comment by afeld** [comment]
Hoping to do more of that validation client-side, at the very least.

https://www.pivotaltracker.com/story/show/98157690

**Comment by jessieay** [comment]
We got client-side validations in via simpleform (https://github.com/18F/C2/pull/656). 

Closing this for now unless there are more specific suggestions around client-side validations that we haven't already implemented.
