### ISSUE TITLE
Updated Email 

### ISSUE THREAD

**Issue by jehlers** [18F/C2#48]
### Current email

![screen shot 2014-09-02 at 2 39 46 pm](https://cloud.githubusercontent.com/assets/4267825/4257534/c523e574-3ac4-11e4-8ea8-3e6efdac0c35.png)

### New email design

Biggest updates:
- Reorganization into 3 columns - Product, Price, Vendor
- Associating the tags with either the product or the vendor
- "Branding" in process. We may or may not keep the Communicart wordmark. For now it is a placeholder.
- Colors are also still in process (as you will see in issue # )

![c2-email-approver](https://cloud.githubusercontent.com/assets/4267825/4257542/d7f43348-3ac4-11e4-98b2-cb0a64a9fca6.png)

### Current approval notification emails

![screen shot 2014-09-02 at 2 40 39 pm](https://cloud.githubusercontent.com/assets/4267825/4257570/452f8d04-3ac5-11e4-8ccc-8911afcf20da.png)

![screen shot 2014-09-02 at 2 41 24 pm](https://cloud.githubusercontent.com/assets/4267825/4257571/47c4ca20-3ac5-11e4-8987-fe5ee2cbe2f1.png)

### New approval notification emails

Biggest updates:
- Pulled the approval notifications into the context of the purchase request 
- 2 columns for the list of users who's approval is pending vs approved - Helps the user follow the process and clearly identify which approvers they are waiting for.

![c2-email-pending](https://cloud.githubusercontent.com/assets/4267825/4257580/5f1924b4-3ac5-11e4-931e-61bdf5ca5ec8.png)

![c2-email-approved](https://cloud.githubusercontent.com/assets/4267825/4257581/653ec704-3ac5-11e4-8e53-914ce6a69818.png)

**Comment by jessieay** [comment]
Seems like we are due for another round of email redesigns. At the moment, this seems outdated. But cc @amberwreed as a reference for when she thinks through next round of redesign!
