### ISSUE TITLE
Observing request data

### ISSUE THREAD

**Issue by ethanheppner** [18F/C2#501]
Hello again C2 team!

18F TeamOps has found Communicart really helpful and is thinking a little more about "what's next". We are thinking of ways to easily explore the data generated by the many requests made by an organization. Here are a few of our needs:

- Tracking purchases by office, so we know what has and hasn't been requested (avoiding duplication).
- Tracking purchases by spending, so we can make sure that we aren't exceeding any limits.
- Having a record of purchases that other requestors and P-card holders can reference, so we can ensure that we're ultimately requesting and ordering the same quality of products.
- Being able to reference requests across multiple users that have been modified and/or denied, so we can maybe come up with some guidelines.
- Tracking order status from pending approval to delivered and recorded in inventory.

A few of these ideas have been mentioned in other issues, but consider this as a more "global" issue of considering how to assess what data an organization will need to pull from Communicart. Here is my idea:

For all 18F requests from the general staff, we can use <a href="https://docs.google.com/a/gsa.gov/forms/d/1Lk9lhIrL1AaN-uGmMbEkH6GlxsuYD6xYm12XMb7Tfn8/viewform">this Google form</a>  which will populate <a href="https://docs.google.com/spreadsheets/d/1C2Q-Mc_SEi-pwToRX2z5CDQjCam7S-F2ZSTD8EYJvPk/edit#gid=923302428">this sheet</a>.

TeamOps staff can then use Communicart to get Ric's approval, and we use the additional fields provided in the sheet to track order status, approvals, and arrival confirmation in inventory. Would it be helpful for you all if we switched to this system so that you could easily observe how we interact with the data that we need?

**Comment by phirefly** [comment]
Thanks Ethan! I will transfer these into our tracker here: https://www.pivotaltracker.com/n/projects/1149728. You can easily see which ones I've already logged by searching for '18F' in the search. My understanding from Ric is that C2 would be used by everyone, but we can talk about that in another forum.

**Comment by afeld** [comment]
To clarify: we do _have_ all of that information – it's just a matter of having a page(s) to present it. One band-aid may be to allow exporting all past requests to CSV, so that TeamOps can do whatever analysis they want within a spreadsheet program?

**Comment by ethanheppner** [comment]
+Kathryn

Hi Aidan,

Being able to export past requests to CSV would be huge for us, especially
if we added additional fields to the request form like product type
(software, office supplies, etc.), client billable to (if applicable), and
status (approved, denied, awaiting purchase, awaiting delivery, delivered
and confirmed in inventory, etc.).

Thanks!

Ethan

On Mon, Jul 27, 2015 at 10:53 AM, Aidan Feldman <notifications@github.com>
wrote:

> To clarify: we do *have* all of that information – it's just a matter of
> having a page(s) to present it. One band-aid may be to allow exporting all
> past requests to CSV, so that TeamOps can do whatever analysis they want
> within a spreadsheet program?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/C2/issues/501#issuecomment-125252640>.
>



-- 
Ethan Heppner
Operations Specialist
https://18f.gsa.gov/
U.S. General Services Administration

**Comment by afeld** [comment]
The good news is that implement CSV exporting is separate from adding additional fields – it's easy to include new fields in the CSV once the functionality is in place.

> product type (software, office supplies, etc.)

We can totally do that. What are the all of the types?

> client billable to (if applicable)

Storied: https://www.pivotaltracker.com/story/show/99920650

> status (approved, denied, awaiting purchase, awaiting delivery, delivered and confirmed in inventory, etc.)

This one is a bit tricker. Tracking in https://github.com/18F/C2/issues/492.

**Comment by bipartisanMas0n** [comment]
Switching to this system would be easier for purposes of my novice understanding of coding and data feilds, in general. It would speed up the learning process, 99.9%

**Comment by bipartisanMas0n** [comment]
CSV is the wisest option; owned by MCP_independent; Modesto, CA 95350

**Comment by jessieay** [comment]
I am currently adding "product type" via https://www.pivotaltracker.com/story/show/108105962

Closing this since there are tracker stories for each element requested. thanks all! :rainbow:
