### ISSUE TITLE
Instructions for formatting new submissions

### ISSUE THREAD

**Issue by jameshupp** [18F/C2#531]
This is a potentially huge help topic, but I think it's both easier to describe/write and easier for the user if it exists within the submission form. Instructions provided with the form itself are more likely to be noticed and followed.

As an example, the current dollar amount (actual or estimated) requires submissions to be formatted without commas, as in `9999.99` or `9999` rather than `9,999.99` or `9,999`. Under "Amount" but above the actual form, a micro-instruction like `Do not use commas. (Example: 1050.25)`.

If there are other submission fields that might have similar points of confusion, put the instruction briefly with that field. If the instruction is too long (more than, say 50 characters) insert a link to a help topic elsewhere.

**Comment by bipartisanMas0n** [comment]
I will speak on this subject more when I get my meds refilled, I suffer from Chronic Migraines...

**Comment by jessieay** [comment]
Added a tracker story for this here https://www.pivotaltracker.com/story/show/108497694

Closing this issue - thanks for raising the issue. Agreed that we should have a default / suggested value for amount so people know what format to use
