### ISSUE TITLE
Web Experience

### ISSUE THREAD

**Issue by jehlers** [18F/C2#55]
The web experience for Communicart is a place where users can see all of their pending purchase requests, and all past purchase requests. There are two main user groups: Requesters and Approvers. 

#### Home screen / Portal Page

**For the approver:**
- They can see both pending requests they need to respond to, and all past requests they have approved.

![c2-web-01-approver1](https://cloud.githubusercontent.com/assets/4267825/4529919/cc2cf9ae-4d7b-11e4-85bd-7b8721e584d8.png)

**For the requester:**
- Same as the approver except that they see who they sent their requests to.

![c2-web-01-requester1](https://cloud.githubusercontent.com/assets/4267825/4529947/0f021192-4d7c-11e4-9da5-cce7e4734b67.png)

#### Pending request page

**For the approver:**
- Similar to the email (may have gotten to this page from the email)
- Allows the user to comment or ask questions (or reject the request). The comments will be sent back and forth to the users through email and also be collected on this page.

![c2-web-01-approver2](https://cloud.githubusercontent.com/assets/4267825/4529968/59b7f9c2-4d7c-11e4-9828-dc8ddd0766cc.png)

**For the requester:**
- Same as approver except they see who they are waiting for approval from.

![c2-web-01-requester2](https://cloud.githubusercontent.com/assets/4267825/4529976/6dffa63c-4d7c-11e4-950f-d8a2e3ab1ce8.png)

#### Archived request

So far this page is the same for Approvers and Requesters except for the header on the page. 

The only thing I haven't designed yet, is the ability to upload receipts and other documents that can help confirm that the purchase has been made.

![c2-web-01-approved](https://cloud.githubusercontent.com/assets/4267825/4530006/b4df04d0-4d7c-11e4-94e4-82c3fc36a850.png)

**The main thing that isn't working right now,** is the pending and approved status bugs. I need to keep playing with the styling of those.

**Comment by jessieay** [comment]
cc @amberwreed this is related to what you're working on!
