### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by vzvenyach** [18F/C2#560]
Looking over the [API documentation](https://github.com/18F/C2/blob/master/doc/api.md), I noticed that the documentation has outdated URLs and does not describe the authentication/authorization flow. Thanks!

**Comment by afeld** [comment]
I think it's still up-to-date...it's just not enabled because it doesn't have auth :blush: 

```
$ bin/rake routes | grep api
    api_ncr_work_orders GET    /api/v1/ncr/work_orders(.:format)                  api/ncr/work_orders#index
              api_users GET    /api/v1/users(.:format)                            api/users#index
```

**Comment by afeld** [comment]
...but if it's needed for something sooner than later, let us know and we can prioritize!
