### ISSUE TITLE
Tests fail in the Auckland timezone

### ISSUE THREAD

**Issue by istanfield09** [18F/C2#633]
If Zonebie chooses Auckland as its random timezone, two tests will fail. Any other time zone will not (to my knowledge) cause these tests to fail. 

In particular: 
`rspec ./spec/mailers/communicart_mailer_spec.rb:78 # CommunicartMailer actions_for_approver creates a new token`
`rspec ./spec/models/api_token_spec.rb:16 # ApiToken.create sets the expiry`

This bug can be reproduced by running the tests in the Auckland timezone manually:
`ZONEBIE_TZ="Auckland" rspec`

**Comment by pkarman** [comment]
Thanks @istanfield09 -- can you verify if #636 fixes this problem?

**Comment by istanfield09** [comment]
Looks good! #636 fixes the bug, all tests are green on my machine.
